export default [
  // { label: 'All', value: 'all' },
  { label: '10-K', value: '10-K', searchFroms: ['10-k.P1.*', '10-k.P2.*', '10-k.P3.*', '10-k.P4.*']},
  { label: '10-K/A', value: '10-K/A',searchFroms: ['10-K/A.*']},
  { label: '10-K405', value: '10-K405' ,searchFroms:['10-K405.*']},
  { label: '10-K405/A', value: '10-K405/A',searchFroms:['10-K405/A.*']},
  { label: '10-KT', value: '10-KT', searchFroms: ['10-KT.*']},
  { label: '10-KT/A', value: '10-KT/A',searchFroms: ['10-KT/A.*']},
  { label: '10-Q', value: '10-Q', searchFroms: ['10-q.P1.*', '10-q.P2.*']},
  { label: '10-Q/A', value: '10-Q/A',searchFroms:['10-Q/A.*']},
  { label: '10-QT', value: '10-QT' ,searchFroms:['10-QT.*']},
  { label: '10-QT/A', value: '10-QT/A',searchFroms:['10-QT/A.*']},
  { label: '10QSB', value: '10QSB',searchFroms:['10QSB.*']},
  { label: '20-F', value: '20-F',searchFroms:['20-F.*']},
  { label: '20-F/A', value: '20-F/A' ,searchFroms:['20-F/A.*']},
  { label: '40-F', value: '40-F' ,searchFroms:['40-F.*']},
  { label: '40-F/A', value: '40-F/A' ,searchFroms:['40-F/A.*']},
  { label: '6-K', value: '6-K',searchFroms:['6-K.*']},
  { label: '6-K/A', value: '6-K/A',searchFroms:['6-K/A.*']},
  { label: '8-K', value: '8-K',searchFroms:['8-K.*']},
  { label: '8-K/A', value: '8-K/A',searchFroms:['8-K/A.*']},
  { label: '8-K12B', value: '8-K12B' ,searchFroms:['8-K12B.*']},
  { label: '8-K12B/A', value: '8-K12B/A',searchFroms:['8-K12B/A.*']},
  { label: '8-K12G3', value: '8-K12G3',searchFroms:['8-K12G3.*']},
  { label: '8-K12G3/A', value: '8-K12G3/A',searchFroms:['8-K12G3/A.*']},
  { label: '8-K15D5', value: '8-K15D5',searchFroms:['8-K15D5.*']},
  { label: 'AR', value: 'AR' ,searchFroms:['AR.*']},
  { label: 'ARS/A', value: 'ARS/A' ,searchFroms:['ARS/A.*']},
  { label: 'CORR', value: 'CORR',searchFroms:['CORR.*']},
  { label: 'DEF 14A', value: 'DEF 14A',searchFroms:['1DEF 14A.*']},
  { label: 'EP', value: 'EP',searchFroms:['EP.*']},
  { label: 'ER', value: 'ER' ,searchFroms:['ER.*']},
  { label: 'FIN SUPP', value: 'FIN SUPP' ,searchFroms:['FIN SUPP.*']},
  { label: 'Intierra SR', value: 'Intierra SR' ,searchFroms:['Intierra SR.*']},
  { label: 'Intl Offer', value: 'Intl Offer',searchFroms:['Intl Offer.*'] },
  { label: 'MEG - AR', value: 'MEG - AR' ,searchFroms:['MEG - AR.*']},
  { label: 'NT 10-Q', value: 'NT 10-Q',searchFroms:['NT 10-Q*']},
  { label: 'OC', value: 'OC',searchFroms:['10-Q/A.*']},
  { label: 'Other Financials', value: 'Other Financials' ,searchFroms:['Other Financials.*']},
  { label: 'pdf', value: 'pdf',searchFroms:['Pdf.*']},
  { label: 'PR', value: 'PR' ,searchFroms:['PR.*']},
  { label: 'QR', value: 'QR',searchFroms:['QR.*']},
  { label: 'QR/A', value: 'QR/A',searchFroms:['QR/A.*']},
  { label: 'SR', value: 'SR',searchFroms:['SR.*']},
  { label: 'Tanshin', value: 'Tanshin',searchFroms:['Tanshin.*']}
];
