export default [
  // { label: 'All', value: 'all' },
  { label: '10-K', value: '10-K', searchFroms: ['10-k.p1.*', '10-k.p2.*', '10-k.p3.*', '10-k.p4.*'] },
  { label: '10-Q', value: '10-Q', searchFroms: ['10-q.p1.*', '10-q.p2.*'] },
  { label: '8-K', value: '8-K', searchFroms: ['8-k.*'] },
  { label: '40-F', value: '40-F', searchFroms: ['40-f.*'] },
  { label: '20-F', value: '20-F', searchFroms: ['20-f.*'] },
  { label: '6-K', value: '6-K', searchFroms: ['6-k.*'] },
  { label: '10-K/A', value: '10-K/A', searchFroms: ['10-k/a.*'] },
  { label: '10-K405', value: '10-K405', searchFroms: ['10-k405.*'] },
  { label: '10-K405/A', value: '10-K405/A', searchFroms: ['10-k405/a.*'] },
  { label: '10-KT', value: '10-KT', searchFroms: ['10-kt.*'] },
  { label: '10-KT/A', value: '10-KT/A', searchFroms: ['10-kt/a.*'] },
  { label: '10-Q/A', value: '10-Q/A', searchFroms: ['10-q/a.*'] },
  { label: '10-QT', value: '10-QT', searchFroms: ['10-qt.*'] },
  { label: '10-QT/A', value: '10-QT/A', searchFroms: ['10-qt/a.*'] },
  { label: '10QSB', value: '10QSB', searchFroms: ['10qsb.*'] },
  { label: '20-F/A', value: '20-F/A', searchFroms: ['20-f/a.*'] },
  { label: '40-F/A', value: '40-F/A', searchFroms: ['40-f/a.*'] },
  { label: '6-K/A', value: '6-K/A', searchFroms: ['6-k/a.*'] },
  { label: '8-K/A', value: '8-K/A', searchFroms: ['8-k/a.*'] },
  { label: '8-K12B', value: '8-K12B', searchFroms: ['8-k12b.*'] },
  { label: '8-K12B/A', value: '8-K12B/A', searchFroms: ['8-k12b/a.*'] },
  { label: '8-K12G3', value: '8-K12G3', searchFroms: ['8-k12g3.*'] },
  { label: '8-K12G3/A', value: '8-K12G3/A', searchFroms: ['8-k12g3/a.*'] },
  { label: '8-K15D5', value: '8-K15D5', searchFroms: ['8-k15d5.*'] },
  { label: 'AR', value: 'AR', searchFroms: ['ar.*'] },
  { label: 'ARS/A', value: 'ARS/A', searchFroms: ['ars/a.*'] },
  { label: 'CORR', value: 'CORR', searchFroms: ['corr.*'] },
  { label: 'DEF 14A', value: 'DEF 14A', searchFroms: ['1def 14a.*'] },
  { label: 'EP', value: 'EP', searchFroms: ['ep.*'] },
  { label: 'ER', value: 'ER', searchFroms: ['er.*'] },
  { label: 'FIN SUPP', value: 'FIN SUPP', searchFroms: ['fin supp.*'] },
  { label: 'Intierra SR', value: 'Intierra SR', searchFroms: ['intierra sr.*'] },
  { label: 'Intl Offer', value: 'Intl Offer', searchFroms: ['intl offer.*'] },
  { label: 'MEG - AR', value: 'MEG - AR', searchFroms: ['meg - ar.*'] },
  { label: 'NT 10-Q', value: 'NT 10-Q', searchFroms: ['nt 10-q*'] },
  { label: 'OC', value: 'OC', searchFroms: ['10-q/a.*'] },
  { label: 'Other Financials', value: 'Other Financials', searchFroms: ['other financials.*'] },
  { label: 'pdf', value: 'pdf', searchFroms: ['pdf.*'] },
  { label: 'PR', value: 'PR', searchFroms: ['pr.*'] },
  { label: 'QR', value: 'QR', searchFroms: ['qr.*'] },
  { label: 'QR/A', value: 'QR/A', searchFroms: ['qr/a.*'] },
  { label: 'SR', value: 'SR', searchFroms: ['sr.*'] },
  { label: 'Tanshin', value: 'Tanshin', searchFroms: ['tanshin.*'] }
];
