export default {
  '10-K': {
    'main.p1.i1': 'Item 1 - Business',
    'main.p1.i1a': 'Item 1A - Risk Factors',
    'main.p1.i1b': 'Item 1B - Unresolved Staff Comments',
    'main.p1.i2': 'Item 2 - Properties',
    'main.p1.i3': 'Item 3 - Legal Proceedings',
    'main.p1.i4': 'Item 4 - Mine Safety Disclosures',
    'main.p2.i5':
      'Item 5 - Market for Registrants Common Equity, Related Stockholder Matters and Issuer Purchases of Equity Securities',
    'main.p2.i6': 'Item 6 - Selected Finanical Data',
    'main.p2.i7': 'Item 7 - Managements Discussion and Analysis of Financial Condition and Results of Operations',
    'main.p2.i7a': 'Item 7A - Quantitative and Qualitative Disclosures About Market Risk',
    'main.p2.i8': 'Item 8 - Financial Statements and Supplementary Data',
    'main.p2.i9': 'Item 9 - Changes in and Disagreements With Accountants on Accounting and Financial Disclosure',
    'main.p2.i9a': 'Item 9A - Controls and Procedures',
    'main.p2.i9b': 'Item 9B - Other Information',
    'main.p3.i10': 'Item 10 - Directors, Executive Officers and Corporate Governance',
    'main.p3.i11': 'Item 11 - Executive Compensation',
    'main.p3.i12':
      'Item 12 - Security Ownership of Certain Beneficial Owners and Management and Related Stockholder Matters',
    'main.p3.i13': 'Item 13 - Certain Relationships and Related Transactions, and Director Independence',
    'main.p3.i14': 'Item 14 - Principal Accountant Fees and Services',
    'main.p4.i15': 'Item 15 - Exhibits and Finanical Information',
    'main.p4.i16': 'Item 16 - Form 10-K Summary',
    'main.n': 'Notes',
    'main.n.l3-other': 'Notes'
  },
  '10-Q': {
    'main.p1.i1': 'Item 1 - Financial Statements',
    'main.p1.i2': 'Item 2 - Liquidity And Capital Resources',
    'main.p1.i3': 'Item 3 - Quantitative and Qualitative Disclosures About Market Risk',
    'main.p1.i4': 'Item 4 - Controls and Procedures',
    'main.p2.i1': 'Item 1 - Legal Proceedings',
    'main.p2.i1a': 'Item 1A - Risk Factors',
    'main.p2.i2': 'Item 2 - Unregistered Sales of Equity Securities and Use of Proceeds',
    'main.p2.i3': 'Item 3 - Defaults Upon Securities',
    'main.p2.i4': 'Item 4 - Mine Saftey Disclosures',
    'main.p2.i5': 'Item 5 - Other Information',
    'main.p2.i6': 'Item 6 - Exhibits',
    'main.n': 'Notes',
    'main.n.l3-other': 'Notes'
  },
  '8-K': {
    'main.sec1.i101': 'Item 1.01 - Entry into a Material Definitive Agreement',
    'main.sec1.i102': 'Item 1.02 - Termination of a Material Definitive Agreement',
    'main.sec1.i103': 'Item 1.03 - Bankruptcy or Receivership',
    'main.sec1.i104': 'Item 1.04 - Mine Safety - Reporting of Shutdowns and Patterns of Violations',
    'main.sec2.i201': 'Item 2.01 - Completion of Acquisition or Disposition of Assets',
    'main.sec2.i202': 'Item 2.02 - Results of Operations and Financial Condition',
    'main.sec2.i203':
      'Item 2.03 - Creation of a Direct Financial Obligation or an Obligation under an Off-Balance Sheet Arrangement of a Registrant',
    'main.sec2.i204':
      'Item 2.04 - Triggering Events That Accelerate or Increase a Direct Financial Obligation or an Obligation under an Off-Balance Sheet Arrangement',
    'main.sec2.i205': 'Item 2.05 - Costs Associated with Exit or Disposal Activities',
    'main.sec2.i206': 'Item 2.06 - Material Impairments',
    'main.sec3.i301':
      'Item 3.01 - Notice of Delisting or Failure to Satisfy a Continued Listing Rule or Standard, Transfer of Listing',
    'main.sec3.i302': 'Item 3.02 - Unregistered Sales of Equity Securities',
    'main.sec3.i303': 'Item 3.03 - Material Modification to Rights of Security Holders',
    'main.sec4.i401': "Item 4.01 - Changes in Registrant's Certifying Accountant",
    'main.sec4.i402':
      'Item 4.02 - Non-Reliance on Previously Issued Financial Statements or a Related Audit Report or Completed Interim Review',
    'main.sec5.i501': 'Item 5.01 - Changes in Control of Registrant',
    'main.sec5.i502':
      'Item 5.02 - Departure of Directors or Certain Officers, Election of Directors, Appointment of Certain Officers, Compensatory Arrangements of Certain Officers',
    'main.sec5.i503': 'Item 5.03 - Amendments to Articles of Incorporation or Bylaws, Change in Fiscal Year',
    'main.sec5.i504': "Item 5.04 - Temporary Suspension of Trading Under Registrant's Employee Benefit Plans",
    'main.sec5.i505':
      "Item 5.05 - Amendment to Registrant's Code of Ethics, or Waiver of a Provision of the Code of Ethics",
    'main.sec5.i506': 'Item 5.06 - Change in Shell Company Status',
    'main.sec5.i507': 'Item 5.07 - Submission of Matters to a Vote of Security Holders',
    'main.sec5.i508': 'Item 5.08 - Shareholder Director Nominations',
    'main.sec6.i601': 'Item 6.01 - ABS Informational and Computational Material',
    'main.sec6.i602': 'Item 6.02 - Change of Servicer or Trustee',
    'main.sec6.i603': 'Item 6.03 - Change in Credit Enhancement or Other External Support',
    'main.sec6.i604': 'Item 6.04 - Failure to Make a Required Distribution',
    'main.sec6.i605': 'Item 6.05 - Securities Act Updating Disclosure',
    'main.sec7.i701': 'Item 7.01 - Regulation FD Disclosure',
    'main.sec8.i801': 'Item 8.01 - Other Events',
    'main.sec9.i901': 'Item 9.01 - Financial Statements and Exhibits',
    'main.sec3.i801': 'Item 8.01 - Other Matters',
    'main.n.l3-other': 'Notes',
    'main.s': 'Signature',
    ex: 'Exhibits',
    'main.n': 'Notes'
  },
  '20-F': {
    'main.p1.i1': 'Item 1 - Identity of Directors, Senior Management and Advisors',
    'main.p1.i2': 'Item 2 - Offer Statistics',
    'main.p1.i3': 'Item 3 - Key Information',
    'main.p1.i4': 'Item 4 - Information on the Company',
    'main.p1.i5': 'Item 5 - Operating and Financial Review and Prospects',
    'main.p1.i6': 'Item 6 - Directors, Senior Management and Employees',
    'main.p1.i7': 'Item 7 - Major Shareholders and Related Party Transactions',
    'main.p1.i8': 'Item 8 - Financial Information',
    'main.p1.i9': 'Item 9 - The Offer and Listing',
    'main.p1.i10': 'Item 10 - Additional Information',
    'main.p1.i11': 'Item 11 - Quantitative and Qualitative Disclosures About Market Risk',
    'main.p1.i12': 'Item 12 - Description of Securities Other than Equity Securities',
    'main.p2.i13': 'Item 13 - Defaults, Dividend Arrearages and Delinquencies',
    'main.p2.i14': 'Item 14 - Material Modifications to the Rights of Security Holders and Use of Proceeds',
    'main.p2.i15': 'Item 15 - Controls and Procedures',
    'main.p2.i16a': 'Item 16A - Audit Committee Financial Expert',
    'main.p2.i16b': 'Item 16B - Code of Ethics',
    'main.p2.i16c': 'Item 16C - Other Information',
    'main.p2.i16d': 'Item 16D - Exhibits',
    'main.p2.i16e': 'Item 16E - Purchases of Equity Securities by the Issuer and Affiliated Purchasers',
    'main.p2.i16f': "Item 16F - Changes in Registrant's Certifying Accountant",
    'main.p2.i16g': 'Item 16G - Corporate Governance',
    'main.p2.i16h': 'Item 16H - Mine Safety Disclosure',
    'main.p3.i17': 'Item 17 - Financial Statements',
    'main.p3.i18': 'Item 18 - Financial Statements',
    'main.p3.i19': 'Item 19 - Exhibits',
    'main.n.l3-other': 'Notes',
    'main.s': 'Signature',
    ex: 'Exhibits',
    'main.n': 'Notes'
  },
  '10-K/A': {
    'main.p1.i1': 'Item 1 - Business',
    'main.p1.i1a': 'Item 1A - Risk Factors',
    'main.p1.i1b': 'Item 1B - Unresolved Staff Comments',
    'main.p1.i2': 'Item 2 - Properties',
    'main.p1.i3': 'Item 3 - Legal Proceedings',
    'main.p1.i4': 'Item 4 - Mine Safety Disclosures',
    'main.p2.i5':
      'Item 5 - Market for Registrants Common Equity, Related Stockholder Matters and Issuer Purchases of Equity Securities',
    'main.p2.i6': 'Item 6 - Selected Finanical Data',
    'main.p2.i7': 'Item 7 - Managements Discussion and Analysis of Financial Condition and Results of Operations',
    'main.p2.i7a': 'Item 7A - Quantitative and Qualitative Disclosures About Market Risk',
    'main.p2.i8': 'Item 8 - Financial Statements and Supplementary Data',
    'main.p2.i9': 'Item 9 - Changes in and Disagreements With Accountants on Accounting and Financial Disclosure',
    'main.p2.i9a': 'Item 9A - Controls and Procedures',
    'main.p2.i9b': 'Item 9B - Other Information',
    'main.p3.i10': 'Item 10 - Directors, Executive Officers and Corporate Governance',
    'main.p3.i11': 'Item 11 - Executive Compensation',
    'main.p3.i12':
      'Item 12 - Security Ownership of Certain Beneficial Owners and Management and Related Stockholder Matters',
    'main.p3.i13': 'Item 13 - Certain Relationships and Related Transactions, and Director Independence',
    'main.p3.i14': 'Item 14 - Principal Accountant Fees and Services',
    'main.p4.i15': 'Item 15 - Exhibits and Finanical Information',
    'main.p4.i16': 'Item 16 - Form 10-K Summary',
    'main.n': 'Notes',
    'main.n.l3-other': 'Notes'
  }
};
