export default {
  '10-K': {
    'main.n.l3-other': 'Notes',
    'main.p1.i1': 'Business',
    'main.p1.i1112b': 'Significant Obligors of Pool Assets (Financial Information)',
    'main.p1.i1114b2':
      'Credit Enhancement and Other Support, Except for Certain Derivatives Instruments (Information Regarding Significant Enhancement Providers)',
    'main.p1.i1115b': 'Certain Derivatives Instruments (Financial Information)',
    'main.p1.i1117': 'Legal Proceedings',
    'main.p1.i1a': 'Risk Factors',
    'main.p1.i1b': 'Unresolved Staff Comments',
    'main.p1.i2': 'Properties',
    'main.p1.i3': 'Legal Proceedings',
    'main.p1.i4': 'Mine Safety Disclosures',
    'main.p1.i4a': 'Executive Officers of The Registrant',
    'main.p2.i5':
      "Market for Registrant's Common Equity, Related Stockholder Matters and Issuer Purchases of Equity Securities",
    'main.p2.i6': 'Selected Finanical Data',
    'main.p2.i7': "Management's Discussion and Analysis of Financial Condition and Results of Operations",
    'main.p2.i7a': 'Quantitative and Qualitative Disclosures About Market Risk',
    'main.p2.i8': 'Financial Statements and Supplementary Data',
    'main.p2.i9': 'Changes in and Disagreements With Accountants on Accounting and Financial Disclosure',
    'main.p2.i9a': 'Controls and Procedures',
    'main.p2.i9b': 'Other Information',
    'main.p3.i10': 'Directors, Executive Officers and Corporate Governance',
    'main.p3.i11': 'Executive Compensation',
    'main.p3.i1119': 'Affiliations and Certain Relationships and Related Transactions',
    'main.p3.i1122': 'Compliance with Applicable Servicing Criteria',
    'main.p3.i1123': 'Servicer Compliance Statement',
    'main.p3.i12': 'Security Ownership of Certain Beneficial Owners and Management and Related Stockholder Matters',
    'main.p3.i13': 'Certain Relationships and Related Transactions, and Director Independence',
    'main.p3.i14': 'Principal Accountant Fees and Services',
    'main.p4.i15': 'Exhibits and Financial Information',
    'main.p4.i16': 'Form 10-K Summary',
    'main.n': 'Notes'
  },
  '10-Q': {
    'main.p1.i1': 'Financial Statements',
    'main.p1.i2': 'Controls and Procedures',
    'main.p1.i3': 'Quantitative and Qualitative Disclosures About Market Risk',
    'main.p1.i4': 'Controls and Procedures',
    'main.p2.i1': 'Legal Proceedings',
    'main.p2.i1a': 'Risk Factors',
    'main.p2.i2': 'Unregistered Sales of Equity Securities and Use of Proceeds',
    'main.p2.i3': 'Defaults Upon Securities',
    'main.p2.i4': 'Mine Saftey Disclosures',
    'main.p2.i5': 'Other Information',
    'main.p2.i6': 'Exhibits',
    'main.n': 'Notes',
    'main.n.l3-other': 'Notes'
  },
  '8-K': {
    'main.sec1.i101': 'Entry into a Material Definitive Agreement',
    'main.sec1.i102': 'Termination of a Material Definitive Agreement',
    'main.sec1.i103': 'Bankruptcy or Receivership',
    'main.sec1.i104': 'Mine Safety - Reporting of Shutdowns and Patterns of Violations',
    'main.sec2.i201': 'Completion of Acquisition or Disposition of Assets',
    'main.sec2.i202': 'Results of Operations and Financial Condition',
    'main.sec2.i203':
      'Creation of a Direct Financial Obligation or an Obligation under an Off-Balance Sheet Arrangement of a Registrant',
    'main.sec2.i204':
      'Triggering Events That Accelerate or Increase a Direct Financial Obligation or an Obligation under an Off-Balance Sheet Arrangement',
    'main.sec2.i205': 'Costs Associated with Exit or Disposal Activities',
    'main.sec2.i206': 'Material Impairments',
    'main.sec3.i301':
      'Notice of Delisting or Failure to Satisfy a Continued Listing Rule or Standard, Transfer of Listing',
    'main.sec3.i302': 'Unregistered Sales of Equity Securities',
    'main.sec3.i303': 'Material Modification to Rights of Security Holders',
    'main.sec3.i801': 'Other Matters',
    'main.sec4.i401': "Changes in Registrant's Certifying Accountant",
    'main.sec4.i402':
      'Non-Reliance on Previously Issued Financial Statements or a Related Audit Report or Completed Interim Review',
    'main.sec5.i501': 'Changes in Control of Registrant',
    'main.sec5.i502':
      'Departure of Directors or Certain Officers, Election of Directors, Appointment of Certain Officers, Compensatory Arrangements of Certain Officers',
    'main.sec5.i503': 'Amendments to Articles of Incorporation or Bylaws, Change in Fiscal Year',
    'main.sec5.i504': "Temporary Suspension of Trading Under Registrant's Employee Benefit Plans",
    'main.sec5.i505': "Amendment to Registrant's Code of Ethics, or Waiver of a Provision of the Code of Ethics",
    'main.sec5.i506': 'Change in Shell Company Status',
    'main.sec5.i507': 'Submission of Matters to a Vote of Security Holders',
    'main.sec5.i508': 'Shareholder Director Nominations',
    'main.sec6.i601': 'ABS Informational and Computational Material',
    'main.sec6.i602': 'Change of Servicer or Trustee',
    'main.sec6.i603': 'Change in Credit Enhancement or Other External Support',
    'main.sec6.i604': 'Failure to Make a Required Distribution',
    'main.sec6.i605': 'Securities Act Updating Disclosure',
    'main.sec7.i701': 'Regulation FD Disclosure',
    'main.sec8.i801': 'Other Events',
    'main.sec9.i901': 'Financial Statements and Exhibits',
    'main.n.l3-other': 'Notes',
    'main.n': 'Notes'
  },
  '20-F': {
    'main.p1.i1': 'Identity of Directors, Senior Management and Advisors',
    'main.p1.i10': 'Additional Information',
    'main.p1.i11': 'Quantitative and Qualitative Disclosures About Market Risk',
    'main.p1.i12': 'Description of Securities Other than Equity Securities',
    'main.p1.i2': 'Offer Statistics',
    'main.p1.i3': 'Key Information',
    'main.p1.i4': 'Information on the Company',
    'main.p1.i4a': 'Unresolved Staff Comments',
    'main.p1.i5': 'Operating and Financial Review and Prospects',
    'main.p1.i6': 'Directors, Senior Management and Employees',
    'main.p1.i7': 'Major Shareholders and Related Party Transactions',
    'main.p1.i8': 'Financial Information',
    'main.p1.i9': 'The Offer and Listing',
    'main.p2.i13': 'Defaults, Dividend Arrearages and Delinquencies',
    'main.p2.i14': 'Material Modifications to the Rights of Security Holders and Use of Proceeds',
    'main.p2.i15': 'Controls and Procedures',
    'main.p2.i16': 'Reserved',
    'main.p2.i16a': 'Audit Committee Financial Expert',
    'main.p2.i16b': 'Code of Ethics',
    'main.p2.i16c': 'Other Information',
    'main.p2.i16d': 'Exhibits',
    'main.p2.i16e': 'Purchases of Equity Securities by the Issuer and Affiliated Purchasers',
    'main.p2.i16f': "Changes in Registrant's Certifying Accountant",
    'main.p2.i16g': 'Corporate Governance',
    'main.p2.i16h': 'Mine Safety Disclosure',
    'main.p3.i17': 'Financial Statements',
    'main.p3.i18': 'Financial Statements',
    'main.p3.i19': 'Exhibits',
    'main.n.l3-other': 'Notes',
    'main.n': 'Notes'
  }
};
