export default {
"10-k.p1.i1": "Business",
"10-k.p1.i1112b": "Significant Obligors of Pool Assets (Financial Information)",
"10-k.p1.i1114b2": "Credit Enhancement and Other Support, Except for Certain Derivatives Instruments (Information Regarding Significant Enhancement Providers)",
"10-k.p1.i1115b": "Certain Derivatives Instruments (Financial Information)",
"10-k.p1.i1117": "Legal Proceedings",
"10-k.p1.i1a": "Risk Factors",
"10-k.p1.i1b": "Unresolved Staff Comments",
"10-k.p1.i2": "Properties",
"10-k.p1.i3": "Legal Proceedings",
"10-k.p1.i4": "Mine Safety Disclosures",
"10-k.p1.i4a": "Executive Officers of The Registrant",
"10-k.p2.i5": "Market for Registrant's Common Equity, Related Stockholder Matters and Issuer Purchases of Equity Securities",
"10-k.p2.i6": "Selected Finanical Data",
"10-k.p2.i7": "Management's Discussion and Analysis of Financial Condition and Results of Operations",
"10-k.p2.i7a": "Quantitative and Qualitative Disclosures About Market Risk",
"10-k.p2.i8": "Financial Statements and Supplementary Data",
"10-k.p2.i9": "Changes in and Disagreements With Accountants on Accounting and Financial Disclosure",
"10-k.p2.i9a": "Controls and Procedures",
"10-k.p2.i9b": "Other Information",
"10-k.p3.i10": "Directors, Executive Officers and Corporate Governance",
"10-k.p3.i11": "Executive Compensation",
"10-k.p3.i1119": "Affiliations and Certain Relationships and Related Transactions",
"10-k.p3.i1122": "Compliance with Applicable Servicing Criteria",
"10-k.p3.i1123": "Servicer Compliance Statement",
"10-k.p3.i12": "Security Ownership of Certain Beneficial Owners and Management and Related Stockholder Matters",
"10-k.p3.i13": "Certain Relationships and Related Transactions, and Director Independence",
"10-k.p3.i14": "Principal Accountant Fees and Services",
"10-k.p4.i15": "Exhibits and Financial Information",
"10-k.p4.i16": "Form 10-K Summary",
"10-q.p1.i1": "Financial Statements",
"10-q.p1.i2": "Controls and Procedures",
"10-q.p1.i3": "Quantitative and Qualitative Disclosures About Market Risk",
"10-q.p1.i4": "Controls and Procedures",
"10-q.p2.i1": "Legal Proceedings",
"10-q.p2.i1a": "Risk Factors",
"10-q.p2.i2": "Unregistered Sales of Equity Securities and Use of Proceeds",
"10-q.p2.i3": "Defaults Upon Securities",
"10-q.p2.i4": "Mine Saftey Disclosures",
"10-q.p2.i5": "Other Information",
"10-q.p2.i6": "Exhibits",
"8-k.sec1.i101": "Entry into a Material Definitive Agreement",
"8-k.sec1.i102": "Termination of a Material Definitive Agreement",
"8-k.sec1.i103": "Bankruptcy or Receivership",
"8-k.sec1.i104": "Mine Safety - Reporting of Shutdowns and Patterns of Violations",
"8-k.sec2.i201": "Completion of Acquisition or Disposition of Assets",
"8-k.sec2.i202": "Results of Operations and Financial Condition",
"8-k.sec2.i203": "Creation of a Direct Financial Obligation or an Obligation under an Off-Balance Sheet Arrangement of a Registrant",
"8-k.sec2.i204": "Triggering Events That Accelerate or Increase a Direct Financial Obligation or an Obligation under an Off-Balance Sheet Arrangement",
"8-k.sec2.i205": "Costs Associated with Exit or Disposal Activities",
"8-k.sec2.i206": "Material Impairments",
"8-k.sec3.i301": "Notice of Delisting or Failure to Satisfy a Continued Listing Rule or Standard, Transfer of Listing",
"8-k.sec3.i302": "Unregistered Sales of Equity Securities",
"8-k.sec3.i303": "Material Modification to Rights of Security Holders",
"8-k.sec3.i801": "Other Matters",
"8-k.sec4.i401": "Changes in Registrant's Certifying Accountant",
"8-k.sec4.i402": "Non-Reliance on Previously Issued Financial Statements or a Related Audit Report or Completed Interim Review",
"8-k.sec5.i501": "Changes in Control of Registrant",
"8-k.sec5.i502": "Departure of Directors or Certain Officers, Election of Directors, Appointment of Certain Officers, Compensatory Arrangements of Certain Officers",
"8-k.sec5.i503": "Amendments to Articles of Incorporation or Bylaws, Change in Fiscal Year",
"8-k.sec5.i504": "Temporary Suspension of Trading Under Registrant's Employee Benefit Plans",
"8-k.sec5.i505": "Amendment to Registrant's Code of Ethics, or Waiver of a Provision of the Code of Ethics",
"8-k.sec5.i506": "Change in Shell Company Status",
"8-k.sec5.i507": "Submission of Matters to a Vote of Security Holders",
"8-k.sec5.i508": "Shareholder Director Nominations",
"8-k.sec6.i601": "ABS Informational and Computational Material",
"8-k.sec6.i602": "Change of Servicer or Trustee",
"8-k.sec6.i603": "Change in Credit Enhancement or Other External Support",
"8-k.sec6.i604": "Failure to Make a Required Distribution",
"8-k.sec6.i605": "Securities Act Updating Disclosure",
"8-k.sec7.i701": "Regulation FD Disclosure",
"8-k.sec8.i801": "Other Events",
"8-k.sec9.i901": "Financial Statements and Exhibits",
"20-f.p1.i1": "Identity of Directors, Senior Management and Advisors",
"20-f.p1.i10": "Additional Information",
"20-f.p1.i11": "Quantitative and Qualitative Disclosures About Market Risk",
"20-f.p1.i12": "Description of Securities Other than Equity Securities",
"20-f.p1.i2": "Offer Statistics",
"20-f.p1.i3": "Key Information",
"20-f.p1.i4": "Information on the Company",
"20-f.p1.i4a": "Unresolved Staff Comments",
"20-f.p1.i5": "Operating and Financial Review and Prospects",
"20-f.p1.i6": "Directors, Senior Management and Employees",
"20-f.p1.i7": "Major Shareholders and Related Party Transactions",
"20-f.p1.i8": "Financial Information",
"20-f.p1.i9": "The Offer and Listing",
"20-f.p2.i13": "Defaults, Dividend Arrearages and Delinquencies",
"20-f.p2.i14": "Material Modifications to the Rights of Security Holders and Use of Proceeds",
"20-f.p2.i15": "Controls and Procedures",
"20-f.p2.i16": "Reserved",
"20-f.p2.i16a": "Audit Committee Financial Expert",
"20-f.p2.i16b": "Code of Ethics",
"20-f.p2.i16c": "Other Information",
"20-f.p2.i16d": "Exhibits",
"20-f.p2.i16e": "Purchases of Equity Securities by the Issuer and Affiliated Purchasers",
"20-f.p2.i16f": "Changes in Registrant's Certifying Accountant",
"20-f.p2.i16g": "Corporate Governance",
"20-f.p2.i16h": "Mine Safety Disclosure",
"20-f.p3.i17": "Financial Statements",
"20-f.p3.i18": "Financial Statements",
"20-f.p3.i19": "Exhibits"
}
