export default [
  { label: 'All', value: 'all' },
  { label: '10-K', value: '10-K' },
  { label: '10-K/A', value: '10-K/A' },
  { label: '10-K405', value: '10-K405' },
  { label: '10-K405/A', value: '10-K405/A' },
  { label: '10-KT', value: '10-KT' },
  { label: '10-KT/A', value: '10-KT/A' },
  { label: '10-Q', value: '10-Q' },
  { label: '10-Q/A', value: '10-Q/A' },
  { label: '10-QT', value: '10-QT' },
  { label: '10-QT/A', value: '10-QT/A' },
  { label: '10QSB', value: '10QSB' },
  { label: '20-F', value: '20-F' },
  { label: '20-F/A', value: '20-F/A' },
  { label: '40-F', value: '40-F' },
  { label: '40-F/A', value: '40-F/A' },
  { label: '6-K', value: '6-K' },
  { label: '6-K/A', value: '6-K/A' },
  { label: '8-K', value: '8-K' },
  { label: '8-K/A', value: '8-K/A' },
  { label: '8-K12B', value: '8-K12B' },
  { label: '8-K12B/A', value: '8-K12B/A' },
  { label: '8-K12G3', value: '8-K12G3' },
  { label: '8-K12G3/A', value: '8-K12G3/A' },
  { label: '8-K15D5', value: '8-K15D5' },
  { label: 'AR', value: 'AR' },
  { label: 'ARS', value: 'ARS' },
  { label: 'ARS/A', value: 'ARS/A' },
  { label: 'CORR', value: 'CORR' },
  { label: 'DEF 14A', value: 'DEF 14A' },
  { label: 'EP', value: 'EP' },
  { label: 'ER', value: 'ER' },
  { label: 'FIN SUPP', value: 'FIN SUPP' },
  { label: 'Intierra SR', value: 'Intierra SR' },
  { label: 'Intl Offer', value: 'Intl Offer' },
  { label: 'MEG - AR', value: 'MEG - AR' },
  { label: 'NT 10-Q', value: 'NT 10-Q' },
  { label: 'OC', value: 'OC' },
  { label: 'Other Financials', value: 'Other Financials' },
  { label: 'pdf', value: 'pdf' },
  { label: 'PR', value: 'PR' },
  { label: 'QR', value: 'QR' },
  { label: 'QR/A', value: 'QR/A' },
  { label: 'SR', value: 'SR' },
  { label: 'Tanshin', value: 'Tanshin' }
];
